#!/usr/bin/env ts-node
// packages/contracts/scripts/generate-python.ts
// Fix 5 — Option A: reads JOB_SCHEMAS, emits contracts.py with Pydantic v2 models.
//
// Run: pnpm --filter @octo/contracts codegen
// Output: packages/contracts/generated/contracts.py  (committed to repo)
//
// Design decisions:
// - We emit Pydantic v2 (model_config, field validators) not dataclasses.
// - Optional[T] fields map from zod .optional().
// - z.record(z.unknown()) → Dict[str, Any].
// - z.array(T) → List[T].
// - Nested objects become inner Pydantic models with PascalCase names.
// - The file is prefixed with a "DO NOT EDIT" banner + the source commit SHA
//   so Python workers can assert they're running against the right contract version.

import * as fs from 'fs';
import * as path from 'path';
import { zodToJsonSchema } from 'zod-to-json-schema';
import { JOB_SCHEMAS, type JobSchemaName } from '../src/schemas/index';

const OUTPUT_DIR = path.resolve(__dirname, '..', 'generated');
const OUTPUT_FILE = path.join(OUTPUT_DIR, 'contracts.py');

// ─── JSON Schema → Python type mapping ──────────────────────────────────────

type JsonSchema = Record<string, unknown>;

function mapType(schema: JsonSchema, modelName: string, extra: string[]): string {
  const type = schema['type'] as string | undefined;
  const anyOf = schema['anyOf'] as JsonSchema[] | undefined;

  // Optional: anyOf [ {type: X}, {not: {}} ] — zod .optional() pattern
  if (anyOf) {
    const nonNull = anyOf.filter((s) => !('not' in s));
    if (nonNull.length === 1 && nonNull[0]) {
      return `Optional[${mapType(nonNull[0] as JsonSchema, modelName, extra)}]`;
    }
    return 'Any';
  }

  if (schema['$ref']) {
    const ref = (schema['$ref'] as string).split('/').pop() ?? 'Any';
    return ref;
  }

  switch (type) {
    case 'string':
      return 'str';
    case 'integer':
      return 'int';
    case 'number':
      return 'float';
    case 'boolean':
      return 'bool';
    case 'array': {
      const items = schema['items'] as JsonSchema | undefined;
      const inner = items ? mapType(items, modelName, extra) : 'Any';
      return `List[${inner}]`;
    }
    case 'object': {
      const props = schema['properties'] as Record<string, JsonSchema> | undefined;
      if (!props) return 'Dict[str, Any]';
      // Inline object → emit as a separate Pydantic model
      const innerName = modelName;
      emitModel(innerName, schema, extra);
      return innerName;
    }
    default:
      return 'Any';
  }
}

function emitModel(name: string, schema: JsonSchema, lines: string[]): void {
  const props = (schema['properties'] as Record<string, JsonSchema> | undefined) ?? {};
  const required = (schema['required'] as string[] | undefined) ?? [];
  const defs = (schema['$defs'] as Record<string, JsonSchema> | undefined) ?? {};

  // Emit any referenced sub-models first
  for (const [defName, defSchema] of Object.entries(defs)) {
    emitModel(defName, defSchema as JsonSchema, lines);
  }

  lines.push(`class ${name}(BaseModel):`);
  lines.push(`    model_config = ConfigDict(frozen=True)`);
  lines.push('');

  if (Object.keys(props).length === 0) {
    lines.push('    pass');
    lines.push('');
    return;
  }

  for (const [fieldName, fieldSchema] of Object.entries(props)) {
    const isRequired = required.includes(fieldName);
    const description = (fieldSchema as JsonSchema)['description'] as string | undefined;

    // Nested objects get a dedicated inner model named ModelField
    const innerModelName = `${name}${fieldName.charAt(0).toUpperCase()}${fieldName.slice(1)}`;
    let pyType = mapType(fieldSchema as JsonSchema, innerModelName, lines);

    // zod .optional() emits as { anyOf: [...] } — already handled in mapType.
    // Here we additionally handle JSON Schema optional pattern via "required" absence.
    if (!isRequired && !pyType.startsWith('Optional')) {
      pyType = `Optional[${pyType}]`;
    }

    const fieldDefault = isRequired ? '' : ' = None';
    const descPart = description ? `  # ${description}` : '';
    lines.push(`    ${fieldName}: ${pyType}${fieldDefault}${descPart}`);
  }

  lines.push('');
}

// ─── Main ────────────────────────────────────────────────────────────────────

function main(): void {
  const commitSha = process.env['GIT_COMMIT'] ?? 'dev';

  const header = [
    '# DO NOT EDIT — generated by packages/contracts/scripts/generate-python.ts',
    `# Source commit: ${commitSha}`,
    `# Generated at: ${new Date().toISOString()}`,
    '#',
    '# To regenerate: pnpm --filter @octo/contracts codegen',
    '',
    'from __future__ import annotations',
    '',
    'from typing import Any, Dict, List, Optional',
    'from pydantic import BaseModel',
    'from pydantic.config import ConfigDict',
    '',
    '',
  ];

  const modelLines: string[] = [];

  for (const [schemaName, zodSchema] of Object.entries(JOB_SCHEMAS) as [
    JobSchemaName,
    (typeof JOB_SCHEMAS)[JobSchemaName],
  ][]) {
    const jsonSchema = zodToJsonSchema(zodSchema, {
      name: schemaName,
      errorMessages: false,
    }) as JsonSchema;

    const rootSchema = (jsonSchema['definitions']?.[schemaName] ?? jsonSchema) as JsonSchema;
    emitModel(schemaName, rootSchema, modelLines);
  }

  fs.mkdirSync(OUTPUT_DIR, { recursive: true });
  fs.writeFileSync(OUTPUT_FILE, [...header, ...modelLines].join('\n'), 'utf8');

  console.log(`[codegen] contracts.py written to ${OUTPUT_FILE}`);
  console.log(`[codegen] models: ${Object.keys(JOB_SCHEMAS).join(', ')}`);
}

main();
