class ToolRegistryError(Exception): ...


class ToolAlreadyRegisteredError(ToolRegistryError): ...


class ToolNotFoundError(ToolRegistryError): ...


class ToolDisabledError(ToolRegistryError): ...


class ToolNeedsReviewError(ToolRegistryError): ...


class ToolNameInvalidError(ToolRegistryError): ...


class ToolPolicyError(Exception): ...


class ToolInputValidationError(Exception): ...


class ToolOutputValidationError(Exception): ...


class ToolContextValidationError(Exception): ...


class ToolDescriptorHashMismatchError(Exception): ...


class ToolExecutionError(Exception): ...
class ToolTimeoutError(ToolExecutionError): ...
class ToolSubprocessError(ToolExecutionError): ...
class ToolOutputParseError(ToolExecutionError): ...
class ToolAsyncPendingError(ToolExecutionError): ...
class ToolAsyncExpiredError(ToolExecutionError): ...
class ToolReplayBlockedError(ToolExecutionError): ...
class ToolApprovalRequiredError(ToolExecutionError): ...
class ToolSideEffectBlockedError(ToolExecutionError): ...
