class ToolRegistryError(Exception): ...


class ToolAlreadyRegisteredError(ToolRegistryError): ...


class ToolNotFoundError(ToolRegistryError): ...


class ToolDisabledError(ToolRegistryError): ...


class ToolNeedsReviewError(ToolRegistryError): ...


class ToolNameInvalidError(ToolRegistryError): ...


class ToolPolicyError(Exception): ...


class ToolInputValidationError(Exception): ...


class ToolOutputValidationError(Exception): ...


class ToolContextValidationError(Exception): ...


class ToolDescriptorHashMismatchError(Exception): ...
