from __future__ import annotations
import subprocess
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
IN_DIR = ROOT / "packages/contracts/generated/json-schema"
OUT_DIR = ROOT / "apps/runtime-worker/app/contracts/generated"
OUT_DIR.mkdir(parents=True, exist_ok=True)

schemas = sorted(IN_DIR.glob("*.json"))
if not schemas:
    raise SystemExit(f"No schemas found in {IN_DIR}")

for schema in schemas:
    out = OUT_DIR / f"{schema.stem}.py"
    cmd = [
        "datamodel-codegen",
        "--input", str(schema),
        "--input-file-type", "jsonschema",
        "--output", str(out),
        "--target-python-version", "3.11",
        "--output-model-type", "pydantic_v2.BaseModel",
        "--use-annotated",
        "--snake-case-field",
        "--strict-nullable",
    ]
    subprocess.run(cmd, check=True)

init_lines = ["# generated by scripts/generate_pydantic_models.py\n"]
for schema in schemas:
    init_lines.append(f"from .{schema.stem} import *\n")
(OUT_DIR / "__init__.py").write_text("".join(init_lines), encoding="utf-8")
print(f"Generated pydantic models in {OUT_DIR}")
