from __future__ import annotations
import subprocess
from pathlib import Path
import json
import pprint

ROOT = Path(__file__).resolve().parent.parent
IN_DIR = ROOT / "packages/contracts/generated/json-schema"
OUT_DIR = ROOT / "apps/runtime-worker/app/contracts/generated"
OUT_DIR.mkdir(parents=True, exist_ok=True)

schemas = sorted(IN_DIR.glob("*.json"))
if not schemas:
    raise SystemExit(f"No schemas found in {IN_DIR}")

for schema in schemas:
    out = OUT_DIR / f"{schema.stem}.py"
    cmd = [
        "datamodel-codegen",
        "--input", str(schema),
        "--input-file-type", "jsonschema",
        "--output", str(out),
        "--target-python-version", "3.11",
        "--output-model-type", "pydantic_v2.BaseModel",
        "--use-annotated",
        "--snake-case-field",
        "--strict-nullable",
        "--disable-timestamp",
    ]
    subprocess.run(cmd, check=True)

init_lines = ["# generated by scripts/generate_pydantic_models.py\n"]
for schema in schemas:
    init_lines.append(f"from .{schema.stem} import *\n")
fsm_path = ROOT / "packages/contracts/generated/execution-fsm.json"
if not fsm_path.exists():
    raise SystemExit(f"No execution FSM contract found in {fsm_path}")
fsm = json.loads(fsm_path.read_text(encoding="utf-8"))
contract_py = """# generated by scripts/generate_pydantic_models.py from packages/contracts/generated/execution-fsm.json

EXECUTION_STATUSES = {statuses}
EXECUTION_TERMINAL_STATES = {terminal}
EXECUTION_VALID_TRANSITIONS = {transitions}
""".format(
    statuses=pprint.pformat(tuple(fsm["statuses"]), width=100),
    terminal=pprint.pformat(tuple(fsm["terminalStatuses"]), width=100),
    transitions=pprint.pformat({key: tuple(value) for key, value in fsm["transitions"].items()}, width=100),
)
(OUT_DIR / "execution_fsm_contract.py").write_text(contract_py, encoding="utf-8")
init_lines.append("from .execution_fsm_contract import *\n")
(OUT_DIR / "__init__.py").write_text("".join(init_lines), encoding="utf-8")
print(f"Generated pydantic models in {OUT_DIR}")
